#!/usr/bin/env bash

ghome=google.com
gdns=8.8.8.8
gifc=$(ip route | awk '/default/ { print $5 }')
gway=$(ip route | awk '/default/ { print $3 }')

if ping -q -c 5 "$ghome" >/dev/null 2>&1
then
    tput sgr0
    echo ""
    echo -e '\E[1;32m'"You are connected to internet via interface \"$gifc\""
    echo ""
    tput sgr0
    exit 0
else
    if ping -q -c 5 "$gdns" >/dev/null 2>&1
    then
        tput sgr0
        echo ""
        echo -e '\E[1;36m'"Your DNS server(s) does not seem to be responding"
        echo -e '\E[1;36m'"\"/etc/resolv.conf\" file might be of interest to you"
        echo ""
        tput sgr0
        exit 1
    else
        if ping -q -c 5 "$gway" >/dev/null 2>&1
        then
            tput sgr0
            echo ""
            echo -e '\E[1;33m'"Problem seems to be with the ISP. Contact the ISP"
            echo ""
            tput sgr0
            exit 1
        else
            tput sgr0
            echo ""
            echo -e '\E[1;31m'"Can't connect to either your router or your modem"
            echo -e '\E[1;31m'"Make sure the PC's network is properly configured"
            echo -e '\E[1;31m'"Also make sure the router or modem is switched on"
            echo -e '\E[1;31m'"Do check that network cable is correctly attached"
            echo -e '\E[1;31m'"In case of wireless router check the signal level"
            echo ""
            tput sgr0
            exit 1
        fi
    fi
fi
